# Generated by Django 2.2.1 on 2019-05-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('progress', models.DecimalField(decimal_places=0, max_digits=3)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='OrderElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=0, max_digits=3)),
                ('order_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('order_total_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listManagement.OrderList')),
            ],
        ),
    ]
