# Generated by Django 2.1.7 on 2019-04-22 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('money', models.IntegerField(blank=True)),
                ('category', models.IntegerField(blank=True)),
                ('count', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('meals', models.CharField(blank=True, max_length=500)),
                ('progress', models.IntegerField(blank=True)),
                ('other', models.CharField(blank=True, max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='special_meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noman.Meal')),
            ],
        ),
    ]
