# Generated by Django 2.2.2 on 2019-06-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favor',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
