# Generated by Django 2.1.2 on 2019-04-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_meal',
            old_name='count',
            new_name='number',
        ),
    ]
