# Generated by Django 2.1.2 on 2019-05-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('noman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_money',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
