# Generated by Django 2.1.2 on 2019-05-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noman', '0002_auto_20190419_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='QR_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
