# Generated by Django 2.1.2 on 2019-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('noman', '0003_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favor',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
