# Generated by Django 2.1.2 on 2019-06-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favor_order',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
