# Generated by Django 2.1.2 on 2019-06-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_favor_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favor_order',
        ),
    ]
